src/SFundR.Web/ViewModels/ProjectViewModel.cs
namespace SFundR.Web.ViewModels;

public class ProjectViewModel
{
  public List<TimeItemViewModel> Items = new();
  public int Id { get; set; }
  public string? Name { get; set; }
  public string? Description { get; set; }
}

src/SFundR.Web/ViewModels/TimeItemViewModel.cs
using SFundR.Core.ProjectAggregate;

namespace SFundR.Web.ViewModels;

public class TimeItemViewModel
{
  public int Id { get; set; }

  /// <summary>
  ///   Komentarz
  /// </summary>
  public string Comment { get; set; } = string.Empty;

  /// <summary>
  ///   Data
  /// </summary>
  public DateTime Date { get; set; }

  /// <summary>
  ///   liczba godzin
  /// </summary>
  public decimal WorkTimeHours { get; set; }

  /// <summary>
  ///   Czy czas jest zatwierdzony
  /// </summary>
  public bool IsApproved { get; set; }

  /// <summary>
  ///   Data zatwierdzenia
  /// </summary>
  public DateTime ApprovedDateTime { get; set; }

  public static TimeItemViewModel FromTimeItem(TimeItem item)
  {
    return new TimeItemViewModel
    {
      Id = item.Id,
      Comment = item.Comment,
      Date = item.Date,
      WorkTimeHours = item.WorkTimeHours,
      IsApproved = item.IsApproved,
      ApprovedDateTime = item.ApprovedDateTime
    };
  }
}

src/SFundR.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SFundR.Web.Controllers;

/// <summary>
///   A sample MVC controller that uses views.
///   Razor Pages provides a better way to manage view-based content, since the behavior, viewmodel, and view are all in
///   one place,
///   rather than spread between 3 different folders in your Web project. Look in /Pages to see examples.
///   See: https://ardalis.com/aspnet-core-razor-pages-%E2%80%93-worth-checking-out/
/// </summary>
public class HomeController : Controller
{
  public IActionResult Index()
  {
    return View();
  }

  public IActionResult Error()
  {
    return View();
  }
}

src/SFundR.Web/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using SFundR.Core.ProjectAggregate;
using SFundR.Core.ProjectAggregate.Specifications;
using SFundR.SharedKernel.Interfaces;
using SFundR.Web.ViewModels;

namespace SFundR.Web.Controllers;

[Route("[controller]")]
public class ProjectController : Controller
{
  private readonly IRepository<Project> _projectRepository;

  public ProjectController(IRepository<Project> projectRepository)
  {
    _projectRepository = projectRepository;
  }

  // GET project/{projectId?}
  [HttpGet("{projectId:int}")]
  public async Task<IActionResult> Index(int projectId = 1)
  {
    var spec = new ProjectByIdWithItemsSpec(projectId);
    var project = await _projectRepository.GetBySpecAsync(spec);
    if (project == null)
    {
      return NotFound();
    }

    var dto = new ProjectViewModel
    {
      Id = project.Id,
      Name = project.Name,
      Items = project.Items
        .Select(item => TimeItemViewModel.FromTimeItem(item))
        .ToList()
    };
    return View(dto);
  }
}

src/SFundR.Web/Pages/ProjectDetails/Incomplete.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SFundR.Core.ProjectAggregate;
using SFundR.Core.ProjectAggregate.Specifications;
using SFundR.SharedKernel.Interfaces;

namespace SFundR.Web.Pages.ProjectDetails;

public class UnapprovedModel : PageModel
{
  private readonly IRepository<Project> _projectRepository;

  public UnapprovedModel(IRepository<Project> projectRepository)
  {
    _projectRepository = projectRepository;
  }

  public List<TimeItem>? TimeItems { get; set; }

  public async Task OnGetAsync()
  {
    var projectSpec = new ProjectByIdWithItemsSpec(1); // TODO: get from route
    var project = await _projectRepository.GetBySpecAsync(projectSpec);
    if (project == null)
    {
      return;
    }

    var spec = new UnapprovedItemsSpec();

    TimeItems = spec.Evaluate(project.Items).ToList();
  }
}

src/SFundR.Web/Pages/ProjectDetails/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SFundR.Core.ProjectAggregate;
using SFundR.Core.ProjectAggregate.Specifications;
using SFundR.SharedKernel.Interfaces;
using SFundR.Web.ApiModels;

namespace SFundR.Web.Pages.ProjectDetails;

public class IndexModel : PageModel
{
  private readonly IRepository<Project> _projectRepository;

  public IndexModel(IRepository<Project> projectRepository)
  {
    _projectRepository = projectRepository;
  }

  [BindProperty(SupportsGet = true)] public int ProjectId { get; set; }

  public string Message { get; set; } = "";

  public ProjectDTO? Project { get; set; }

  public async Task OnGetAsync()
  {
    var projectSpec = new ProjectByIdWithItemsSpec(ProjectId);
    var project = await _projectRepository.GetBySpecAsync(projectSpec);

    if (project == null)
    {
      Message = "No project found.";
      return;
    }

    Project = new ProjectDTO
    (
      project.Id,
      project.Name,
      project.Description,
      project.Items
        .Select(TimeItemDTO.FromTimeItem)
        .ToList()
    );
  }
}

src/SFundR.Web/Pages/ProjectDetails/Incomplete.cshtml
@page
@model SFundR.Web.Pages.ProjectDetails.UnapprovedModel

<h2>Unapproved To Do Items (Razor Page)</h2>
<ul>
    @if (Model.TimeItems != null)
    {
        @foreach (var item in Model.TimeItems)
        {
            <li>
                @item.Comment
                @if (item.IsApproved)
                {
                    <span>DONE!</span>
                }
                else
                {
                    <span>NOT DONE</span>
                }
                <br/>@item.Date
                <br/>@item.WorkTimeHours
            </li>
        }
    }
</ul>

src/SFundR.Web/Pages/ProjectDetails/Index.cshtml
@page "{ProjectId}"
@model SFundR.Web.Pages.ProjectDetails.IndexModel

@if (!string.IsNullOrEmpty(Model.Message))
{
    <h2>@Model.Message</h2>
}
else
{
    <h2>Project (Razor Page)</h2>

    <h3>Name: @Model.Project?.Name</h3>

    <b>Items:</b>

    <ul>
        @if (Model.Project != null)
        {
            @foreach (var item in Model.Project.Items)
            {
                <li>
                    @item.Comment
                    @if (item.IsApproved)
                    {
                        <span>DONE!</span>
                    }
                    else
                    {
                        <span>NOT DONE</span>
                    }
                    <br/>@item.Date
                </li>
            }
        }
    </ul>
}

src/SFundR.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "SFundR App";
}
<div class="row">
    <div class="col-md-4">
        <h3>APIs</h3>
        Shows both Controller and Endpoint APIs.
        <ul>
            <li>
                <a href="/swagger">API Documentation (Swagger)</a>
            </li>
        </ul>
        <h3>Projects (using Razor Pages)</h3>
        <ul>
            <li>
                <a asp-page="/ProjectDetails/Index" asp-route-ProjectId="1">Show Project ID:1 and its To Do Items</a>
            </li>
            <li>
                <a asp-page="/ProjectDetails/Incomplete">List Incomplete To Do Items</a>
            </li>
        </ul>
        <h3>Projects (using MVC Views)</h3>
        <ul>
            <li>
                <a asp-area="" asp-controller="Project" asp-action="Index" asp-route-projectId="1">Show Project ID:1 and its To Do Items</a>
            </li>
        </ul>
    </div>
</div>

src/SFundR.Web/Views/Project/Index.cshtml
@{
    ViewData["Title"] = "Project Details";
}
@model SFundR.Web.ViewModels.ProjectViewModel
<h2>Project (MVC View)</h2>

<h3>Name: @Model?.Name</h3>

<b>Items:</b>

<ul>
    @if (Model?.Items != null)
    {
        @foreach (var item in Model.Items)
        {
            <li>
                @item.Comment<br/>@item.Date<br/>@item.WorkTimeHours
            </li>
        }
    }
</ul>

src/SFundR.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SFundR.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>
</head>
<body>
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SFundR.Web</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Today.Year - SFundR.Web</p>
    </footer>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@await RenderSectionAsync("scripts", false).ConfigureAwait(false)
</body>
</html>